const client = require("./setup")

const seedDB = async () => {
    try {
        await client.connect()
        console.log("Awaiting seeding 🌱")
        await client.db("words").collection("easy").drop()
        await client.db("words").collection("easy").insertMany([
            { level: 'easy', type: 'article', length: 3, word: 'the' },
            { level: 'easy', type: 'article', length: 2, word: 'an' },
            { level: 'easy', type: 'article', length: 1, word: 'a' },
            { level: 'easy', type: 'noun', length: 3, word: 'fly' },
            { level: 'easy', type: 'noun', length: 3, word: 'dog' },
            { level: 'easy', type: 'noun', length: 3, word: 'cat' },
            { level: 'easy', type: 'noun', length: 4, word: 'bird' },
            { level: 'easy', type: 'noun', length: 4, word: 'fish' },
            { level: 'easy', type: 'noun', length: 4, word: 'bear' },
            { level: 'easy', type: 'noun', length: 4, word: 'tree' },
            { level: 'easy', type: 'noun', length: 5, word: 'house' },
            { level: 'easy', type: 'noun', length: 5, word: 'mouse' },
            { level: 'easy', type: 'noun', length: 5, word: 'chair' },
            { level: 'easy', type: 'noun', length: 5, word: 'snake' },
            { level: 'easy', type: 'noun', length: 5, word: 'table' },
            { level: 'easy', type: 'noun', length: 5, word: 'spoon' },
            { level: 'easy', type: 'noun', length: 5, word: 'lemon' },
            { level: 'easy', type: 'noun', length: 5, word: 'tiger' },
            { level: 'easy', type: 'noun', length: 4, word: 'road' },
            { level: 'easy', type: 'noun', length: 4, word: 'desk' },
            { level: 'easy', type: 'noun', length: 4, word: 'hand' },
            { level: 'easy', type: 'noun', length: 4, word: 'book' },
            { level: 'easy', type: 'noun', length: 4, word: 'ball' },
            { level: 'easy', type: 'noun', length: 4, word: 'road' },
            { level: 'easy', type: 'noun', length: 4, word: 'desk' },
            { level: 'easy', type: 'noun', length: 4, word: 'hand' },
            { level: 'easy', type: 'noun', length: 4, word: 'book' },
            { level: 'easy', type: 'noun', length: 4, word: 'ball' },
            { level: 'easy', type: 'verb', length: 3, word: 'run' },
            { level: 'easy', type: 'verb', length: 3, word: 'eat' },
            { level: 'easy', type: 'verb', length: 4, word: 'jump' },
            { level: 'easy', type: 'verb', length: 4, word: 'swim' },
            { level: 'easy', type: 'verb', length: 4, word: 'play' },
            { level: 'easy', type: 'verb', length: 4, word: 'bake' },
            { level: 'easy', type: 'verb', length: 4, word: 'read' },
            { level: 'easy', type: 'verb', length: 5, word: 'sleep' },
            { level: 'easy', type: 'verb', length: 5, word: 'laugh' },
            { level: 'easy', type: 'verb', length: 4, word: 'work' },
            { level: 'easy', type: 'verb', length: 5, word: 'climb' },
            { level: 'easy', type: 'verb', length: 4, word: 'talk' },
            { level: 'easy', type: 'verb', length: 5, word: 'drink' },
            { level: 'easy', type: 'verb', length: 4, word: 'cook' },
            { level: 'easy', type: 'verb', length: 4, word: 'sing' },
            { level: 'easy', type: 'adjective', length: 3, word: 'big' },
            { level: 'easy', type: 'adjective', length: 3, word: 'red' },
            { level: 'easy', type: 'adjective', length: 3, word: 'hot' },
            { level: 'easy', type: 'adjective', length: 4, word: 'tall' },
            { level: 'easy', type: 'adjective', length: 4, word: 'cold' },
            { level: 'easy', type: 'adjective', length: 4, word: 'fast' },
            { level: 'easy', type: 'adjective', length: 4, word: 'slow' },
            { level: 'easy', type: 'adjective', length: 4, word: 'soft' },
            { level: 'easy', type: 'adjective', length: 4, word: 'hard' },
            { level: 'easy', type: 'adjective', length: 4, word: 'loud' },
            { level: 'easy', type: 'adjective', length: 4, word: 'dark' },
            { level: 'easy', type: 'adjective', length: 4, word: 'fast' },
            { level: 'easy', type: 'adjective', length: 5, word: 'large' },
            { level: 'easy', type: 'adjective', length: 5, word: 'green' },
            { level: 'easy', type: 'adjective', length: 4, word: 'small' },
            { level: 'easy', type: 'adjective', length: 4, word: 'deep' },
            { level: 'easy', type: 'adjective', length: 5, word: 'bright' },
            { level: 'easy', type: 'adverb', length: 3, word: 'now' },
            { level: 'easy', type: 'adverb', length: 4, word: 'soon' },
            { level: 'easy', type: 'adverb', length: 4, word: 'well' },
            { level: 'easy', type: 'adverb', length: 4, word: 'fast' },
            { level: 'easy', type: 'adverb', length: 6, word: 'slowly' },
            { level: 'easy', type: 'adverb', length: 7, word: 'quickly' },
            { level: 'easy', type: 'adverb', length: 5, word: 'often' },
            { level: 'easy', type: 'adverb', length: 4, word: 'here' },
            { level: 'easy', type: 'adverb', length: 5, word: 'there' },
            { level: 'easy', type: 'adverb', length: 4, word: 'soon' },
            { level: 'easy', type: 'adverb', length: 5, word: 'never' },
            { level: 'easy', type: 'adverb', length: 6, word: 'always' },
            { level: 'easy', type: 'adverb', length: 6, word: 'slowly' },
            { level: 'easy', type: 'adverb', length: 7, word: 'quickly' },
            { level: 'easy', type: 'adverb', length: 4, word: 'late' },
            { level: 'easy', type: 'adverb', length: 5, word: 'early' },
            { level: 'easy', type: 'adverb', length: 5, word: 'never' },
            { level: 'easy', type: 'pronoun', length: 1, word: 'I' },
            { level: 'easy', type: 'pronoun', length: 2, word: 'me' },
            { level: 'easy', type: 'pronoun', length: 3, word: 'you' },
            { level: 'easy', type: 'pronoun', length: 2, word: 'he' },
            { level: 'easy', type: 'pronoun', length: 3, word: 'she' },
            { level: 'easy', type: 'pronoun', length: 2, word: 'it' },
            { level: 'easy', type: 'pronoun', length: 2, word: 'we' },
            { level: 'easy', type: 'pronoun', length: 2, word: 'us' },
            { level: 'easy', type: 'pronoun', length: 4, word: 'they' },
            { level: 'easy', type: 'pronoun', length: 2, word: 'them' },
            { level: 'easy', type: 'preposition', length: 2, word: 'in' },
            { level: 'easy', type: 'preposition', length: 2, word: 'on' },
            { level: 'easy', type: 'preposition', length: 2, word: 'at' },
            { level: 'easy', type: 'preposition', length: 2, word: 'by' },
            { level: 'easy', type: 'conjunction', length: 3, word: 'and' },
            { level: 'easy', type: 'conjunction', length: 3, word: 'but' },
            { level: 'easy', type: 'conjunction', length: 2, word: 'or' },
            { level: 'easy', type: 'conjunction', length: 2, word: 'so' },
            { level: 'easy', type: 'conjunction', length: 3, word: 'yet' },
            { level: 'easy', type: 'conjunction', length: 3, word: 'for' },
            { level: 'easy', type: 'conjunction', length: 6, word: 'nor' },
            { level: 'easy', type: 'conjunction', length: 8, word: 'although' },
            { level: 'easy', type: 'conjunction', length: 5, word: 'while' },
            { level: 'easy', type: 'conjunction', length: 7, word: 'because' },
            { level: 'easy', type: 'conjunction', length: 5, word: 'while' },
            { level: 'easy', type: 'conjunction', length: 7, word: 'because' },
            { level: 'easy', type: 'preposition', length: 4, word: 'under' },
            { level: 'easy', type: 'preposition', length: 4, word: 'over' },
            { level: 'easy', type: 'preposition', length: 7, word: 'between' },
            { level: 'easy', type: 'preposition', length: 5, word: 'among' },
            { level: 'easy', type: 'conjunction', length: 8, word: 'although' },
            { level: 'easy', type: 'conjunction', length: 5, word: 'while' },
            { level: 'easy', type: 'preposition', length: 4, word: 'under' },
            { level: 'easy', type: 'preposition', length: 4, word: 'over' },
            { level: 'easy', type: 'preposition', length: 7, word: 'between' },
            { level: 'easy', type: 'preposition', length: 5, word: 'among' },
        ])
        console.log("Database seeded 🌾")
        await client.close()
    } catch (error) {
        console.log(error)
    }
}

seedDB()